### ISSUE TITLE
Support for databases other than SQLite

### ISSUE THREAD

**Issue by RealOrangeOne** [Tricked-dev/vwmetrics#2]
SQLite is great and all, but Vaultwarden supports other database backends. It would be great if other databases were supported to pull metrics from.

**Comment by Tricked-dev** [comment]
Sure i'll be working on adding postgresql & mysql(mariadb) support

**Comment by Tricked-dev** [comment]
should be added in https://github.com/Tricked-dev/vwmetrics/commit/d8115286730e3f630ba3c86c568e859d414cee20 lmk if you have any problems
