### ISSUE TITLE
Wrong prometheus metric type

### ISSUE THREAD

**Issue by NguyenHuy93** [Tricked-dev/vwmetrics#6]
Prometheus cannot read the result of vwmetrics because there is an error in your script which is metric type. You used "TYPE guage" instead of "TYPE gauge".

**Comment by Tricked-dev** [comment]
thanks for bringing that up i'll go fix it

**Comment by Tricked-dev** [comment]
fixed in https://github.com/Tricked-dev/vwmetrics/commit/3582f35f4881d9c111ba3070a60884dd5fb67977
