### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by kosssi** [Tricked-dev/vwmetrics#7]
Thanks for this services.
Can you share your grafana Dashboard ?

**Comment by Tricked-dev** [comment]
![image](https://github.com/Tricked-dev/vwmetrics/assets/72335827/99595148-ceb0-4968-9d74-1bc0b236bb8d)
This is what i made

**Comment by kosssi** [comment]
I had seen the screenshot ;) I was talking more about the dashboard in JSON

**Comment by GeekCornerGH** [comment]
I guess [this](https://github.com/Tricked-dev/vwmetrics/blob/master/.github/dash.json) is what you're looking for

**Comment by kosssi** [comment]
Thanks a lot !
